// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCENc3hqx5HzjemSIr8VkGoAkhOHYLXHWk',
    appId: '1:801605756069:web:c179150db43b74b259d94c',
    messagingSenderId: '801605756069',
    projectId: 'mymoneyhub18',
    authDomain: 'mymoneyhub18.firebaseapp.com',
    storageBucket: 'mymoneyhub18.firebasestorage.app',
    measurementId: 'G-P4DPHGHQCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfSqVdvFuGirgZLsHYg0iMqnJ-DNkv_Y8',
    appId: '1:801605756069:android:a2ed16e20f158beb59d94c',
    messagingSenderId: '801605756069',
    projectId: 'mymoneyhub18',
    storageBucket: 'mymoneyhub18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzq2y6Pj2g87l5iHyrKeFw_uG-clEqg0Q',
    appId: '1:801605756069:ios:2645d8a9cc51f77f59d94c',
    messagingSenderId: '801605756069',
    projectId: 'mymoneyhub18',
    storageBucket: 'mymoneyhub18.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzq2y6Pj2g87l5iHyrKeFw_uG-clEqg0Q',
    appId: '1:801605756069:ios:2645d8a9cc51f77f59d94c',
    messagingSenderId: '801605756069',
    projectId: 'mymoneyhub18',
    storageBucket: 'mymoneyhub18.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCENc3hqx5HzjemSIr8VkGoAkhOHYLXHWk',
    appId: '1:801605756069:web:148dd174ba08a17b59d94c',
    messagingSenderId: '801605756069',
    projectId: 'mymoneyhub18',
    authDomain: 'mymoneyhub18.firebaseapp.com',
    storageBucket: 'mymoneyhub18.firebasestorage.app',
    measurementId: 'G-NQ4HF4EH4E',
  );
}
